USE [Configurateur]
GO

/****** Object:  Table [dbo].[ref_type]    Script Date: 2026-04-20 10:26:13 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ref_type](
	[UID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[nom] [nvarchar](50) NULL,
 CONSTRAINT [ref_type_PK] PRIMARY KEY CLUSTERED 
(
	[UID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

